<a href="https://colab.research.google.com/github/brandnewmin/brandnewm/blob/master/sess4_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'1.15.0'

In [3]:
!pip uninstall tensorflow

Uninstalling tensorflow-2.3.0:
  Would remove:
    /usr/local/bin/estimator_ckpt_converter
    /usr/local/bin/saved_model_cli
    /usr/local/bin/tensorboard
    /usr/local/bin/tf_upgrade_v2
    /usr/local/bin/tflite_convert
    /usr/local/bin/toco
    /usr/local/bin/toco_from_protos
    /usr/local/lib/python3.6/dist-packages/tensorflow-2.3.0.dist-info/*
    /usr/local/lib/python3.6/dist-packages/tensorflow/*
Proceed (y/n)? y
  Successfully uninstalled tensorflow-2.3.0


In [5]:
!pip install tensorflow==1.15

     |████████████████████████████████| 412.3MB 35kB/s 
     |████████████████████████████████| 51kB 6.6MB/s 
     |████████████████████████████████| 512kB 47.7MB/s 
     |████████████████████████████████| 3.8MB 46.5MB/s 
  Created wheel for gast: filename=gast-0.2.2-cp36-none-any.whl size=7542 sha256=7c0320e321fb7a19cb340f0d230a92235a1fbb8ab78ba9647bc92bb51b4e53f6
  Stored in directory: /root/.cache/pip/wheels/5c/2e/7e/a1d4d4fcebe6c381f378ce7743a3ced3699feb89bcfbdadadd
Successfully built gast
ERROR: tensorflow-probability 0.11.0 has requirement gast>=0.3.2, but you'll have gast 0.2.2 which is incompatible.
  Found existing installation: tensorflow-estimator 2.3.0
    Uninstalling tensorflow-estimator-2.3.0:
      Successfully uninstalled tensorflow-estimator-2.3.0
  Found existing installation: tensorboard 2.3.0
    Uninstalling tensorboard-2.3.0:
      Successfully uninstalled tensorboard-2.3.0
  Found existing installation: gast 0.3.3
    Uninstalling gast-0.3.3:
      Successfully 

In [3]:
tf.set_random_seed(777)

In [7]:
x_data = [[73.,80.,75.],
          [93.,88.,93.],
          [89.,91.,90.],
          [96.,98.,100.],
          [73.,66.,70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

In [9]:
X = tf.placeholder(tf.float32, shape=[None,3])
Y = tf.placeholder(tf.float32, shape=[None,1])

In [10]:
W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [11]:
hypothesis = tf.matmul(X,W) + b
#matmul ? 

In [12]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [14]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [16]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [18]:
for step in range(2001):
  cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X:x_data, Y:y_data})
  if step % 10 == 0 :
    print(step, 'Cost:',cost_val, '\nPrediction:\n', hy_val)

0 Cost: 41.78869 
Prediction:
 [[146.82658]
 [178.01863]
 [174.8947 ]
 [185.78944]
 [140.23361]]
10 Cost: 4.5219717 
Prediction:
 [[152.22903]
 [184.50711]
 [181.29039]
 [192.75485]
 [145.18094]]
20 Cost: 4.516665 
Prediction:
 [[152.24786]
 [184.52495]
 [181.31036]
 [192.77733]
 [145.19273]]
30 Cost: 4.511784 
Prediction:
 [[152.25041]
 [184.52321]
 [181.31108]
 [192.77881]
 [145.18965]]
40 Cost: 4.506942 
Prediction:
 [[152.25293]
 [184.52144]
 [181.31174]
 [192.78021]
 [145.18654]]
50 Cost: 4.502031 
Prediction:
 [[152.25539]
 [184.51965]
 [181.31236]
 [192.7816 ]
 [145.18336]]
60 Cost: 4.4971786 
Prediction:
 [[152.25783]
 [184.51782]
 [181.31296]
 [192.78296]
 [145.1802 ]]
70 Cost: 4.4924026 
Prediction:
 [[152.26035]
 [184.51608]
 [181.31363]
 [192.7844 ]
 [145.17715]]
80 Cost: 4.4875784 
Prediction:
 [[152.26277]
 [184.51431]
 [181.31427]
 [192.78575]
 [145.174  ]]
90 Cost: 4.4828033 
Prediction:
 [[152.2652 ]
 [184.51253]
 [181.31491]
 [192.78714]
 [145.1709 ]]
100 Cost: 4.4780