<a href="https://colab.research.google.com/github/brandnewmin/brandnewm/blob/master/session7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'1.15.0'

In [3]:
!pip uninstall tensorflow

Uninstalling tensorflow-2.3.0:
  Would remove:
    /usr/local/bin/estimator_ckpt_converter
    /usr/local/bin/saved_model_cli
    /usr/local/bin/tensorboard
    /usr/local/bin/tf_upgrade_v2
    /usr/local/bin/tflite_convert
    /usr/local/bin/toco
    /usr/local/bin/toco_from_protos
    /usr/local/lib/python3.6/dist-packages/tensorflow-2.3.0.dist-info/*
    /usr/local/lib/python3.6/dist-packages/tensorflow/*
Proceed (y/n)? y
  Successfully uninstalled tensorflow-2.3.0


In [5]:
!pip install tensorflow==1.15

     |████████████████████████████████| 412.3MB 21kB/s 
     |████████████████████████████████| 51kB 5.1MB/s 
     |████████████████████████████████| 512kB 36.6MB/s 
     |████████████████████████████████| 3.8MB 43.4MB/s 
  Created wheel for gast: filename=gast-0.2.2-cp36-none-any.whl size=7542 sha256=912f1a3a676f0e5da2693665ff486d3ad510d96d94660c48cadf1c748730e0a3
  Stored in directory: /root/.cache/pip/wheels/5c/2e/7e/a1d4d4fcebe6c381f378ce7743a3ced3699feb89bcfbdadadd
Successfully built gast
ERROR: tensorflow-probability 0.11.0 has requirement gast>=0.3.2, but you'll have gast 0.2.2 which is incompatible.
  Found existing installation: tensorflow-estimator 2.3.0
    Uninstalling tensorflow-estimator-2.3.0:
      Successfully uninstalled tensorflow-estimator-2.3.0
  Found existing installation: gast 0.3.3
    Uninstalling gast-0.3.3:
      Successfully uninstalled gast-0.3.3
  Found existing installation: tensorboard 2.3.0
    Uninstalling tensorboard-2.3.0:
      Successfully uninsta

In [3]:
tf.set_random_seed(777)

In [4]:
x_data = [[1,2,1],[1,3,2],[1,3,4],[1,5,5],
          [1,7,5],[1,2,5],[1,6,6],[1,7,7]]
y_data = [[0,0,1],[0,0,1],[0,0,1],
          [0,1,0],[0,1,0],[0,1,0],
          [1,0,0],[1,0,0],[1,0,0]]

In [5]:
x_test =  [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]

In [6]:
X = tf.placeholder("float", [None,3])
Y = tf.placeholder("float",[None,3])

In [7]:
W = tf.Variable(tf.random_normal([3,3]))
b = tf.Variable(tf.random_normal([3]))

In [8]:
hypothesis = tf.nn.softmax(tf.matmul(X,W)+b)

In [9]:
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))

In [10]:
optimal = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [12]:
prediction = tf.argmax(hypothesis, 1)
is_correct = tf.equal(prediction, tf.argmax(Y,1))
accuracy = tf.reduce_mean(tf.cast(is_correct,tf.float32))

In [ ]:
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer()) #

  for step in range(201):
    cost_val, W_val, _ = sess.run([cost,W,optimal], feed_dict={X:x_data, Y: y_data})
    print(step,cost_Val, W_val)
  print("Prediction : ", sess.run(prediction, feed_dict={X:x_test}))
  print("AccuRACY :", sess.run(accuracy), feed_dict={X:x_data, Y:y_data})

########################

In [16]:
import numpy as np

In [18]:
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973], #2행
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],  #3행
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],  #4행
               [816, 820.958984, 1008100, 815.48999, 819.23999],  #5행
               [819.359985, 823, 1188100, 818.469971, 818.97998],  #6행
               [819, 823, 1198100, 816, 820.450012],  #7행
               [811.700012, 815.25, 1098100, 809.780029, 813.669983], #8행
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])  #9행
               #1열       #2열          #3열    #4열        #5열

In [23]:
x_data = xy[:, 0:-1]
y_data = xy[:,[-1]]

In [28]:
XX = tf.placeholder(tf.float32, shape=[None,4])
YY = tf.placeholder(tf.float32, shape=[None,1])

In [29]:
W = tf.Variable(tf.random_normal([4,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [30]:
hypothesis2 = tf.matmul(X,W) + b
#hypothesis2 = tf.nn.softmax(tf.matmul(X,W) + b)

ValueError: ignored

In [31]:
cost2= tf.reduce_mean(tf.square(hypothesis2 - Y))

NameError: ignored

In [32]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [33]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [ ]:
for step in range(201):
  cost_val, hy_val, _ = sess.run([cost2,hypothesis2,train], feed_dict={X:x_data, Y:y_data})
  print(step, "Cost:",cost_val, "\nPrediction:\n", hy_val)

#############################################

In [34]:
def min_max_scaler(data):
  numerator = data-np.min(data,0)
  denominator = np.max(data,0) - np.min(data,0)
  return numerator / (denominator + 1e-7)

In [36]:
xy3 = np.array(
    [
        [828.659973, 833.450012, 908100, 828.349976, 831.659973],
        [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
        [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
        [816, 820.958984, 1008100, 815.48999, 819.23999],
        [819.359985, 823, 1188100, 818.469971, 818.97998],
        [819, 823, 1198100, 816, 820.450012],
        [811.700012, 815.25, 1098100, 809.780029, 813.669983],
        [809.51001, 816.659973, 1398100, 804.539978, 809.559998],
    ]
) #행렬 : 8 * 5

In [37]:
xy3 = min_max_scaler(xy3)
print(xy3)

[[0.99999999 0.99999999 0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881782 0.83755791]
 [0.54412549 0.50274824 0.57608696 0.606468   0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.42582389 0.30434783 0.58504805 0.42624401]
 [0.49556179 0.42582389 0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]


In [39]:
x_data = xy3[:,0:-1]
y_data = xy3[:,[-1]]

In [40]:
X = tf.placeholder(tf.float32, shape=[None,4])
Y = tf.placeholder(tf.float32, shape=[None,1])

In [45]:
W = tf.Variable(tf.random_normal([4,1], name='weight'))
b = tf.Variable(tf.random_normal([1]), name='bias')

In [47]:
hypothesis3 = tf.matmul(X,W) + b

In [48]:
cost3 = tf.reduce_mean(tf.square(hypothesis3 - Y))

In [49]:
train3= tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost3)

In [50]:
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())

  for step in range(101):
    _, cost_val, hy_val = sess.run(
        [train3, cost3, hypothesis3], feed_dict={X:x_data, Y:y_data}
    )
    print(step, "Cost:",cost_val,'\nPrediction:\n', hy_val)

0 Cost: 2.856231 
Prediction:
 [[2.1643527]
 [3.5874953]
 [2.595638 ]
 [1.5331168]
 [2.0152755]
 [1.9285139]
 [1.2778398]
 [1.7916161]]
1 Cost: 1.2392161 
Prediction:
 [[1.3753889]
 [2.781703 ]
 [1.9276507]
 [1.0202208]
 [1.4081426]
 [1.3399508]
 [0.870607 ]
 [1.3777621]]
2 Cost: 0.61463785 
Prediction:
 [[0.8981614 ]
 [2.279999  ]
 [1.5133642 ]
 [0.7041696 ]
 [1.0336943 ]
 [0.97629917]
 [0.6154413 ]
 [1.1139371 ]]
3 Cost: 0.36914152 
Prediction:
 [[0.6131731 ]
 [1.9661922 ]
 [1.2558218 ]
 [0.50971377]
 [0.8029618 ]
 [0.7515838 ]
 [0.4543579 ]
 [0.94305575]]
4 Cost: 0.26868942 
Prediction:
 [[0.44662327]
 [1.7685132 ]
 [1.095135  ]
 [0.39037228]
 [0.66099197]
 [0.61269903]
 [0.35153532]
 [0.8298481 ]]
5 Cost: 0.22396478 
Prediction:
 [[0.35293674]
 [1.6426296 ]
 [0.99431014]
 [0.31743437]
 [0.57384074]
 [0.5268422 ]
 [0.2848422 ]
 [0.7525202 ]]
6 Cost: 0.20086718 
Prediction:
 [[0.3039723 ]
 [1.5611576 ]
 [0.9304971 ]
 [0.2731653 ]
 [0.52054244]
 [0.47375137]
 [0.24060313]
 [0.69760174

######################################

# no.4

In [51]:
import matplotlib.pyplot as plt
import random

In [52]:
tf.set_random_seed(777)

In [53]:
from tensorflow.exaples.tutorials.mnist import input_data

ModuleNotFoundError: ignored

In [ ]:
mnist = input_data.read_data_sets('mnist_data', one_not=True)

In [ ]:
nb_classes = 10

In [ ]:
X = tf.placeholder(tf.flaot32, [None,784])
Y = tf.placeholder(tf.float32, [None, nb_classes])

In [ ]:
W = tf.Variable(tf.random_normal([784, nb_classes]))
b = tf.Variable(tf.random_normal([nb_classes]))

In [ ]:
hypothesis4 = tf.nn.softmax(tf.matmul(X,W)+b)

In [ ]:
cost4 = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis4), axis=1))
train4 = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [ ]:
is_correct4 = tf.equal(tf.armax(hypothesis,1), tf.argmax(,Y,1))
accuracy4 = tf.reduce_mean(tf.cast(is.correct4, tf.float32))

In [ ]:
num_epochs = 15
batch_size = 100
num_iteration = int(mnist.train.num_examples / batch_size)

In [ ]:
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  for epoch in range(num_epochs):
    avg_cost = 0
      
      for i in range(num_iterations):
        batch_xs, batch_ys = mnist.train.next_batch(batch_size)
        _, cost_val = sess.run([train4, cost4], feed_dict={X:batch_xs, Y:batch_ys})
        # 이상한데 ? 쁠등 기호가 왜 있어? avg_coast += coast_val / num_iterations
      print("Epoch : {:04d}, Cost : {:9f}".formal(epoch+1, avg_cost))
   print('learning finished')

   print("Accuracy :", accuracy.eval(
       session=sess,feed_dict={X:mnist.test.images, Y:mnist.test.labels}
         ),
   )

   r = random.randint(0, mnist.test.num_examples - 1)
   print("label : ", sess.run(tf.argmax(mnist.test.labels[r:r+1],1)))
   print(
       "Prediction:", sess.run(tf.argmax(hypothesis4,1), feed_dict={X:mnist.test.images[r:r+1]}),
   )

   plt.imshow(
       mnist.test.images=[r:r+1].reshape(28,28)
       cmap='Greys', interpolation='nearest'
   )
   plt.show()