<a href="https://colab.research.google.com/github/brandnewmin/brandnewm/blob/master/sess4_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'1.15.0'

In [4]:
!pip uninstall tensorflow

Uninstalling tensorflow-2.3.0:
  Would remove:
    /usr/local/bin/estimator_ckpt_converter
    /usr/local/bin/saved_model_cli
    /usr/local/bin/tensorboard
    /usr/local/bin/tf_upgrade_v2
    /usr/local/bin/tflite_convert
    /usr/local/bin/toco
    /usr/local/bin/toco_from_protos
    /usr/local/lib/python3.6/dist-packages/tensorflow-2.3.0.dist-info/*
    /usr/local/lib/python3.6/dist-packages/tensorflow/*
Proceed (y/n)? y
  Successfully uninstalled tensorflow-2.3.0


In [7]:
!pip install tensorflow==1.15

     |████████████████████████████████| 412.3MB 22kB/s 
     |████████████████████████████████| 3.8MB 45.6MB/s 
     |████████████████████████████████| 512kB 43.6MB/s 
     |████████████████████████████████| 51kB 6.5MB/s 
  Created wheel for gast: filename=gast-0.2.2-cp36-none-any.whl size=7542 sha256=eff2e0570e1a428613e98a44f0dfa6cda5bfb4f1e1a57bc8f923b25f87e6c55a
  Stored in directory: /root/.cache/pip/wheels/5c/2e/7e/a1d4d4fcebe6c381f378ce7743a3ced3699feb89bcfbdadadd
Successfully built gast
ERROR: tensorflow-probability 0.11.0 has requirement gast>=0.3.2, but you'll have gast 0.2.2 which is incompatible.
  Found existing installation: tensorboard 2.3.0
    Uninstalling tensorboard-2.3.0:
      Successfully uninstalled tensorboard-2.3.0
  Found existing installation: tensorflow-estimator 2.3.0
    Uninstalling tensorflow-estimator-2.3.0:
      Successfully uninstalled tensorflow-estimator-2.3.0
  Found existing installation: gast 0.3.3
    Uninstalling gast-0.3.3:
      Successfully 

In [4]:
tf.set_random_seed(777)

In [6]:
x1_data = [73.,93.,89.,96.,73,]
x2_data = [80.,88.,91.,98.,66.]
x3_data = [75.,93.,90.,100.,70.]

In [7]:
y_data = [152.,185.,180.,196.,142.]

In [11]:
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

In [12]:
Y = tf.placeholder(tf.float32)

In [14]:
w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]),name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')
#tf.Variable
#tf.random_normal
#tf.random_normal([1])

In [15]:
hypothesis = x1*w1 + x2*w2 + x3*w3 + b

In [17]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))
#비용함수 : 가설(추정식)-실제값 = 잔차 / 잔차 제곱, 합/ 그리고 전체 데이터 수로 나눠서 평균 / 비용함수 최소화가 목표

In [18]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
#최적화(비용함수의 최적화된 추정량을 구하는 방식) : 경사하강법, 알파 = learning_rate : 한 번에 움직이는 정도

In [19]:
train = optimizer.minimize(cost)
#비용함수를 가장 작게 만드는 게 목표

In [21]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
#세션만들기
#placeholder 랑 차이
#global , initializer

In [23]:
for step in range(2001) :
  cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                 feed_dict = {x1 : x1_data, x2:x2_data, x3:x3_data, Y:y_data})
  #2000번 계산 / 세 변수에 위에서 계산한 값 대입(session)
  #feed_dict : 먹이?
  if step % 10 == 0:
    print(step, "Cost :", cost_val, "\nPrediction:\n", hy_val)
  #2000번 계산을 전부 출력하는게 아니라, 10의 배수 계산 결과만 출력하라 / 몇번째 단계, 문자그대로 출력, cost에 해당하는 값, 띄어쓰고 예측값, 가설(가설이 예측값 계산이니깐)

0 Cost : 2.035505 
Prediction:
 [149.467   185.81331 179.66298 197.707   141.73073]
10 Cost : 2.0319057 
Prediction:
 [149.47012 185.81123 179.664   197.7072  141.72847]
20 Cost : 2.02831 
Prediction:
 [149.47325 185.80916 179.66505 197.7074  141.72621]
30 Cost : 2.0247335 
Prediction:
 [149.47636 185.80708 179.66608 197.70758 141.72394]
40 Cost : 2.0211806 
Prediction:
 [149.47946 185.80501 179.66708 197.70776 141.72168]
50 Cost : 2.0176458 
Prediction:
 [149.48256 185.80295 179.6681  197.70796 141.71945]
60 Cost : 2.0141034 
Prediction:
 [149.48564 185.80087 179.66911 197.70811 141.7172 ]
70 Cost : 2.0105896 
Prediction:
 [149.48872 185.79881 179.67012 197.7083  141.71498]
80 Cost : 2.0071158 
Prediction:
 [149.49179 185.79677 179.67114 197.7085  141.71274]
90 Cost : 2.0036378 
Prediction:
 [149.49486 185.79472 179.67215 197.70868 141.71053]
100 Cost : 2.0001724 
Prediction:
 [149.49791 185.79268 179.67316 197.70885 141.70831]
110 Cost : 1.9967302 
Prediction:
 [149.50096 185.79065 1