<a href="https://colab.research.google.com/github/brandnewmin/brandnewm/blob/master/tsf4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'1.15.0'

In [4]:
!pip uninstall tensorflow

Uninstalling tensorflow-2.3.0:
  Would remove:
    /usr/local/bin/estimator_ckpt_converter
    /usr/local/bin/saved_model_cli
    /usr/local/bin/tensorboard
    /usr/local/bin/tf_upgrade_v2
    /usr/local/bin/tflite_convert
    /usr/local/bin/toco
    /usr/local/bin/toco_from_protos
    /usr/local/lib/python3.6/dist-packages/tensorflow-2.3.0.dist-info/*
    /usr/local/lib/python3.6/dist-packages/tensorflow/*
Proceed (y/n)? y
  Successfully uninstalled tensorflow-2.3.0


In [5]:
!pip install tensorflow==1.15

     |████████████████████████████████| 412.3MB 38kB/s 
     |████████████████████████████████| 512kB 35.2MB/s 
     |████████████████████████████████| 3.8MB 53.4MB/s 
     |████████████████████████████████| 51kB 5.0MB/s 
  Created wheel for gast: filename=gast-0.2.2-cp36-none-any.whl size=7540 sha256=70c2abb1bff6e7518a2d7eec914d118c1f2936244583bb3ad1ccf3b104fd0906
  Stored in directory: /root/.cache/pip/wheels/5c/2e/7e/a1d4d4fcebe6c381f378ce7743a3ced3699feb89bcfbdadadd
Successfully built gast
ERROR: tensorflow-probability 0.11.0 has requirement gast>=0.3.2, but you'll have gast 0.2.2 which is incompatible.
  Found existing installation: tensorflow-estimator 2.3.0
    Uninstalling tensorflow-estimator-2.3.0:
      Successfully uninstalled tensorflow-estimator-2.3.0
  Found existing installation: tensorboard 2.3.0
    Uninstalling tensorboard-2.3.0:
      Successfully uninstalled tensorboard-2.3.0
  Found existing installation: gast 0.3.3
    Uninstalling gast-0.3.3:
      Successfully 

theme4. (2020.08.12)

In [ ]:
#데이터 정의
x1_data = [73.,93.,89.,96.,73.] #원래 데이터의 열벡터
#1행 5열 형태 데이터임. 출력과 다름
x2_data = [80.,88.,91.,98.,66.]
x3_data = [75.,93.,90.,100.,70.]
y_data = [152.,185.,180.,196.,142.]

In [ ]:
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

In [ ]:
#이 방법을 대처할 새로운 표현
#행렬 곱하기로 표현하기
x_data = [[73.,80.,75.],[3.,88.,93.],[89.,91.,90.],[96.,98.,100.],[73.,66.,70.]]
y_data = [[152.],[185.],[180.],[196.],[142.]]
#앞에 표현한 데이터 정의랑 [괄호] 안 값이 다름. 원래 데이터 그대로 행벡터 표현

In [ ]:
w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name = 'weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [ ]:
hypothesis = x1*w1 + x2*w2 + x3*w3 + b

In [ ]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [ ]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [ ]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [ ]:
for step in range(2001):
  cost_val,hy_val,_ = sess.run([cost,hypothesis,train], feed_dict={x1:x1_data, x2:x2_data, x3:x3_data, Y:y_data})
  #위에를 해석하지 못했어
  if step % 10 == 0:
    print(step, "Cost:", cost_val, "|nPrediction:|n", hy_val) #print() 안에 것들을 모두 출력하라

0 Cost: 121855.5 |nPrediction:|n [-153.96667 -192.68448 -185.76456 -203.58374 -147.91972]
10 Cost: 869.57654 |nPrediction:|n [153.71352 177.15753 178.63043 193.2262  134.1908 ]
20 Cost: 868.152 |nPrediction:|n [154.62737 178.28914 179.7288  194.41527 135.06815]
30 Cost: 867.83624 |nPrediction:|n [154.6131  178.30513 179.72801 194.40733 135.09451]
40 Cost: 867.5213 |nPrediction:|n [154.59605 178.31766 179.72388 194.39575 135.11823]
50 Cost: 867.2074 |nPrediction:|n [154.57909 178.3302  179.71979 194.38422 135.1419 ]
60 Cost: 866.8945 |nPrediction:|n [154.56216 178.34267 179.71571 194.3727  135.16554]
70 Cost: 866.5823 |nPrediction:|n [154.54527 178.35509 179.71162 194.36115 135.1891 ]
80 Cost: 866.2712 |nPrediction:|n [154.52846 178.3675  179.70757 194.34964 135.21262]
90 Cost: 865.9609 |nPrediction:|n [154.5117  178.37987 179.70352 194.33817 135.2361 ]
100 Cost: 865.65173 |nPrediction:|n [154.49498 178.39218 179.6995  194.32668 135.25949]
110 Cost: 865.34314 |nPrediction:|n [154.47833 

In [ ]:
#수업이랑 약간 다른듯?

4.2

In [3]:
import numpy as np

In [4]:
tf.set_random_seed(777)

In [8]:
#구글 드라이브에서 파일 다운로드
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [12]:
#구글 드라이브에서 파일 다운로드(2)
import os
os.chdir('/content/drive/My Drive/tensorflow') #구글 드라이브 경로지정
%ls

data-01-test-score.csv  tensorflow0.ipynb  tsf1.ipynb  tsf2-3.ipynb


In [18]:
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
print(xy)

[[ 73.  80.  75. 152.]
 [ 93.  88.  93. 185.]
 [ 89.  91.  90. 180.]
 [ 96.  98. 100. 196.]
 [ 73.  66.  70. 142.]
 [ 53.  46.  55. 101.]
 [ 69.  74.  77. 149.]
 [ 47.  56.  60. 115.]
 [ 87.  79.  90. 175.]
 [ 79.  70.  88. 164.]
 [ 69.  70.  73. 141.]
 [ 70.  65.  74. 141.]
 [ 93.  95.  91. 184.]
 [ 79.  80.  73. 152.]
 [ 70.  73.  78. 148.]
 [ 93.  89.  96. 192.]
 [ 78.  75.  68. 147.]
 [ 81.  90.  93. 183.]
 [ 88.  92.  86. 177.]
 [ 78.  83.  77. 159.]
 [ 82.  86.  90. 177.]
 [ 86.  82.  89. 175.]
 [ 78.  83.  85. 175.]
 [ 76.  83.  71. 149.]
 [ 96.  93.  95. 192.]]


In [21]:
#슬라이싱
x_data = xy[:,0:-1]
y_data = xy[:,[-1]]
print(x_data)
print(y_data)

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]]
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]


In [23]:
X = tf.placeholder(tf.float32,shape=[None,3])
Y = tf.placeholder(tf.float32,shape=[None,1])

In [27]:
W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [29]:
hypothesis = tf.matmul(X,W) + b

In [34]:
cost = tf.reduce_mean(tf.square(hypothesis - Y)) #비용함수 : 제곱합 평균 으로 표현했음 (최소제곱법과 같은 형태)

In [37]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5) #경사하강법(GradientDescentOptimizer)
train = optimizer.minimize(cost) #비용함수를 가장 작게 만드는 경사하강법인가?

In [40]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [43]:
for step in range(2001):
  cost_val, hy_val, _=sess.run([cost, hypothesis, train], feed_dict={X:x_data, Y:y_data})
  if step % 10 == 0:
    print(step, "Cost:", cost_val, "|nPrediction:|n", hy_val)

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
 [186.62447 ]
 [182.3054  ]
 [197.94983 ]
 [143.6345  ]
 [105.41205 ]
 [146.46246 ]
 [106.079414]
 [174.4483  ]
 [160.59294 ]
 [142.65353 ]
 [141.83359 ]
 [188.99556 ]
 [158.18599 ]
 [147.54276 ]
 [188.53104 ]
 [152.34663 ]
 [174.6364  ]
 [179.7936  ]
 [160.44167 ]
 [172.38281 ]
 [174.31813 ]
 [164.25903 ]
 [155.42227 ]
 [193.18866 ]]
20 Cost: 19.888765 |nPrediction:|n [[152.66779]
 [186.62102]
 [182.3011 ]
 [197.95186]
 [143.62651]
 [105.41659]
 [146.47379]
 [106.10147]
 [174.45345]
 [160.6126 ]
 [142.65775]
 [141.8406 ]
 [188.98424]
 [158.16699]
 [147.55496]
 [188.53389]
 [152.3206 ]
 [174.65405]
 [179.78163]
 [160.43211]
 [172.39378]
 [174.32141]
 [164.26753]
 [155.40286]
 [193.18181]]
30 Cost: 19.802309 |nPrediction:|n [[152.6644 ]
 [186.6176 ]
 [182.29684]
 [197.95392]
 [143.61855]
 [105.42111]
 [146.48508]
 [106.12349]
 [174.45856]
 [160.63219]
 [142.66196]
 [141.84761]
 [188.97296]
 [158.1481 ]
 [147.56715]
 [188.53673]
 [152.29468]
 [174.6716

4.4

In [44]:
filename_queue = tf.train.string_input_producer(
    ['data-01-test-score.csv'], shuffle=False, name='filename_queue')

Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(string_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(input_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensors(tensor).repeat(num_epochs)`.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
