<a href="https://colab.research.google.com/github/brandnewmin/brandnewm/blob/master/tsf6_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'1.15.0'

In [3]:
!pip uninstall tensorflow

Uninstalling tensorflow-2.3.0:
  Would remove:
    /usr/local/bin/estimator_ckpt_converter
    /usr/local/bin/saved_model_cli
    /usr/local/bin/tensorboard
    /usr/local/bin/tf_upgrade_v2
    /usr/local/bin/tflite_convert
    /usr/local/bin/toco
    /usr/local/bin/toco_from_protos
    /usr/local/lib/python3.6/dist-packages/tensorflow-2.3.0.dist-info/*
    /usr/local/lib/python3.6/dist-packages/tensorflow/*
Proceed (y/n)? y
  Successfully uninstalled tensorflow-2.3.0


In [5]:
!pip install tensorflow==1.15

     |████████████████████████████████| 412.3MB 33kB/s 
     |████████████████████████████████| 51kB 5.1MB/s 
     |████████████████████████████████| 512kB 38.3MB/s 
     |████████████████████████████████| 3.8MB 31.6MB/s 
  Created wheel for gast: filename=gast-0.2.2-cp36-none-any.whl size=7542 sha256=8cf823d3764a049212f5cc6bf169c8d8eb9becb2ffa6b27f5c3caa7c8a49b4ef
  Stored in directory: /root/.cache/pip/wheels/5c/2e/7e/a1d4d4fcebe6c381f378ce7743a3ced3699feb89bcfbdadadd
Successfully built gast
ERROR: tensorflow-probability 0.11.0 has requirement gast>=0.3.2, but you'll have gast 0.2.2 which is incompatible.
  Found existing installation: gast 0.3.3
    Uninstalling gast-0.3.3:
      Successfully uninstalled gast-0.3.3
  Found existing installation: tensorflow-estimator 2.3.0
    Uninstalling tensorflow-estimator-2.3.0:
      Successfully uninstalled tensorflow-estimator-2.3.0
  Found existing installation: tensorboard 2.3.0
    Uninstalling tensorboard-2.3.0:
      Successfully uninsta

In [3]:
tf.set_random_seed(777)

In [4]:
x_data = [[1,2,1,1],[2,1,3,2],[3,1,3,4],[4,1,5,5],[1,7,5,5],[1,2,5,6],[1,6,6,6],[1,7,7,7]]
y_data = [[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]] #one-hot encoding : 이 중에 한 개만 핫하게(=1) 핫하지 않으면(=0)

In [5]:
X = tf.placeholder("float", [None,4])
Y = tf.placeholder("float", [None,3])
nb_classes = 3

In [7]:
W = tf.Variable(tf.random_normal([4,nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

In [8]:
hypothesis = tf.nn.softmax(tf.matmul(X,W)+b)

In [9]:
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis), axis=1))

In [10]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [20]:
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer()) #초기화

  for step in range(2001):
    _, cost_val = sess.run([optimizer, cost], feed_dict={X:x_data,Y:y_data})

    if step % 200 ==0:
      print(step,cost_val)
    print('-----------------')
    a = sess.run(hypothesis, feed_dict = {X:[[1,11,7,9]]}) #새로운 값을 주고 예측하시오
    print(a, sess.run(tf.arg_max(a,1))) #arg_max : argument 중에 어떤게 가장 큰 값이가요? [0,1,2](위치)
"""
    print('-----------------')
    b = sess.run(hypothesis, feed_dict = {X:[[1,3,4,3]]})
    print(b, sess.run(tf.argmax(b,1)))

    print('------------------')
    c = sess.run(hypothesis,feed_dict = {X:[[1,1,0,1]]})
    print(c, sess.run(tf.argmax(c,1)))

    print('--------------------')
    all = sess.run(hypothesis, feed_dict = {X:[[1,11,7,9],[1,3,4,3],[1,1,0,1]]})
    print(all, sess.run(tf.argmax(all,1)))
"""
#내 계산은 끝도 없이 긴데 나만 그런지 확인

0 6.926112
-----------------
[[2.2772072e-06 1.8590171e-08 9.9999774e-01]] [2]
-----------------
[[4.448561e-05 6.721945e-05 9.998883e-01]] [2]
-----------------
[[4.4942204e-05 8.1784790e-03 9.9177659e-01]] [2]
-----------------
[[3.1520767e-04 2.0652886e-04 9.9947828e-01]] [2]
-----------------
[[3.9990100e-05 5.3640762e-03 9.9459594e-01]] [2]
-----------------
[[6.2440359e-04 2.1639666e-04 9.9915922e-01]] [2]
-----------------
[[6.6258806e-05 4.2746360e-03 9.9565911e-01]] [2]
-----------------
[[1.3362976e-03 3.5429760e-04 9.9830937e-01]] [2]
-----------------
[[1.0726327e-04 3.9943890e-03 9.9589831e-01]] [2]
-----------------
[[2.5474224e-03 5.9551024e-04 9.9685705e-01]] [2]
-----------------
[[1.7368703e-04 4.2567998e-03 9.9556953e-01]] [2]
-----------------
[[4.4481666e-03 9.8926376e-04 9.9456257e-01]] [2]
-----------------
[[2.7796836e-04 5.0537148e-03 9.9466830e-01]] [2]
-----------------
[[0.00726704 0.00158931 0.9911437 ]] [2]
-----------------
[[4.4122915e-04 6.5302886e-03 9

KeyboardInterrupt: ignored